### ISSUE TITLE
how to dismiss NDialog programmatically

### ISSUE THREAD

**Issue by wmhseir3** [nizwar/ndialog#11] opened 2022-04-12 07:31 UTC
as seen in title. there is no dismiss method as with the NDialog. 
is there any way to do so now or in the next release?
thanks.

**Comment by ChandAbdullah** [comment] 2022-04-27 12:43
in NAlertDialog, how to dismiss dialog programmatically?
Please provider us.

**Comment by nizwar** [comment] 2022-04-28 08:36
You can use Navigator.pop(context) to NAlertDialog, and use .dismiss() on ProgressDialog.. i'll close this issues as
duplicate of #8

**Closed as completed** 2022-04-28 08:37 UTC
Labels: duplicate
